In [ ]:
#    TEST NOTEBOOK + TEST TRIES
#    SO I DON'T BREAK REAL ONE

In [10]:
import os
import csv
import pandas as pd

school_path = os.path.join("raw_data", "schools_complete.csv") 
school_df = pd.read_csv(school_path)
stu_path = os.path.join("raw_data", "students_complete.csv") 
students_df = pd.read_csv(stu_path)

passing_rate = 60

In [3]:
students_df

,Student ID,name,gender,grade,school,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
7,7,Nicole Baker,F,12th,Huang High School,96,69
8,8,Michael Roth,M,10th,Huang High School,95,87
9,9,Matthew Greene,M,10th,Huang High School,96,84
10,10,Andrew Alexander,M,10th,Huang High School,90,70
11,11,Daniel Cooper,M,10th,Huang High School,78,77
12,12,Brittney Walker,F,9th,Huang High School,64,79
13,13,William Long,M,9th,Huang High School,71,79
14,14,Tammy Hebert,F,10th,Huang High School,85,67
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88
16,16,Donald Zamora,M,9th,Huang High School,88,55
17,17,Kimberly Santiago,F,9th,Huang High School,74,75
18,18,Kevin Stevens,M,9th,Huang High School,64,69
19,19,Brandi Lyons,F,9th,Huang High School,89,80
20,20,Lisa Davis,F,10th,Huang High School,91,89
21,21,Kristen Lopez,F,10th,Huang High School,90,77
22,22,Kimberly Stewart,F,11th,Huang High School,99,84
23,23,Christopher Parker,M,9th,Huang High School,81,68
24,24,Chelsea Griffith,F,11th,Huang High School,85,73
25,25,Cesar Morris,M,9th,Huang High School,92,70
26,26,Melanie Decker,F,9th,Huang High School,63,85
27,27,Tracey Oconnor,F,10th,Huang High School,80,58
28,28,Kelly James,F,11th,Huang High School,73,55
29,29,Nicole Brown,F,12th,Huang High School,90,88
...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73
39152,39152,Lori Moore,F,9th,Thomas High School,98,84
39153,39153,William Hubbard,M,9th,Thomas High School,80,75
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71
39155,39155,John Brooks,M,10th,Thomas High School,92,98
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86
39161,39161,April Reyes,F,10th,Thomas High School,70,84
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77
39163,39163,John Reese,M,11th,Thomas High School,90,75
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

In [3]:
school_df

    School ID                   name      type  size   budget
0           0      Huang High School  District  2917  1910635
1           1   Figueroa High School  District  2949  1884411
2           2    Shelton High School   Charter  1761  1056600
3           3  Hernandez High School  District  4635  3022020
4           4    Griffin High School   Charter  1468   917500
5           5     Wilson High School   Charter  2283  1319574
6           6    Cabrera High School   Charter  1858  1081356
7           7     Bailey High School  District  4976  3124928
8           8     Holden High School   Charter   427   248087
9           9       Pena High School   Charter   962   585858
10         10     Wright High School   Charter  1800  1049400
11         11  Rodriguez High School  District  3999  2547363
12         12    Johnson High School  District  4761  3094650
13         13       Ford High School  District  2739  1763916
14         14     Thomas High School   Charter  1635  1043130

In [8]:
#school_df = school_df.rename(columns = {"name":"school"})
#school_df
merge_table = pd.merge(school_df, students_df, on="school")
merge_table

,School ID,school,type,size,budget,Student ID,name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
1,0,Huang High School,District,2917,1910635,1,Victor Smith,M,12th,94,61
2,0,Huang High School,District,2917,1910635,2,Kevin Rodriguez,M,12th,90,60
3,0,Huang High School,District,2917,1910635,3,Dr. Richard Scott,M,12th,67,58
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84
5,0,Huang High School,District,2917,1910635,5,Bryan Miranda,M,9th,94,94
6,0,Huang High School,District,2917,1910635,6,Sheena Carter,F,11th,82,80
7,0,Huang High School,District,2917,1910635,7,Nicole Baker,F,12th,96,69
8,0,Huang High School,District,2917,1910635,8,Michael Roth,M,10th,95,87
9,0,Huang High School,District,2917,1910635,9,Matthew Greene,M,10th,96,84
10,0,Huang High School,District,2917,1910635,10,Andrew Alexander,M,10th,90,70
11,0,Huang High School,District,2917,1910635,11,Daniel Cooper,M,10th,78,77
12,0,Huang High School,District,2917,1910635,12,Brittney Walker,F,9th,64,79
13,0,Huang High School,District,2917,1910635,13,William Long,M,9th,71,79
14,0,Huang High School,District,2917,1910635,14,Tammy Hebert,F,10th,85,67
15,0,Huang High School,District,2917,1910635,15,Dr. Jordan Carson,M,11th,94,88
16,0,Huang High School,District,2917,1910635,16,Donald Zamora,M,9th,88,55
17,0,Huang High School,District,2917,1910635,17,Kimberly Santiago,F,9th,74,75
18,0,Huang High School,District,2917,1910635,18,Kevin Stevens,M,9th,64,69
19,0,Huang High School,District,2917,1910635,19,Brandi Lyons,F,9th,89,80
20,0,Huang High School,District,2917,1910635,20,Lisa Davis,F,10th,91,89
21,0,Huang High School,District,2917,1910635,21,Kristen Lopez,F,10th,90,77
22,0,Huang High School,District,2917,1910635,22,Kimberly Stewart,F,11th,99,84
23,0,Huang High School,District,2917,1910635,23,Christopher Parker,M,9th,81,68
24,0,Huang High School,District,2917,1910635,24,Chelsea Griffith,F,11th,85,73
25,0,Huang High School,District,2917,1910635,25,Cesar Morris,M,9th,92,70
26,0,Huang High School,District,2917,1910635,26,Melanie Decker,F,9th,63,85
27,0,Huang High School,District,2917,1910635,27,Tracey Oconnor,F,10th,80,58
28,0,Huang High School,District,2917,1910635,28,Kelly James,F,11th,73,55
29,0,Huang High School,District,2917,1910635,29,Nicole Brown,F,12th,90,88
...,...,...,...,...,...,...,...,...,...,...,...
39140,14,Thomas High School,Charter,1635,1043130,39140,Cheyenne Hernandez,F,9th,76,99
39141,14,Thomas High School,Charter,1635,1043130,39141,Jonathan Sullivan,M,10th,86,93
39142,14,Thomas High School,Charter,1635,1043130,39142,Deborah Higgins DDS,F,10th,96,83
39143,14,Thomas High School,Charter,1635,1043130,39143,Steven Jackson,M,11th,71,93
39144,14,Thomas High School,Charter,1635,1043130,39144,Cristian Webster,M,12th,77,87
39145,14,Thomas High School,Charter,1635,1043130,39145,Audrey Fry,F,10th,94,74
39146,14,Thomas High School,Charter,1635,1043130,39146,Michael Carroll,M,9th,69,95
39147,14,Thomas High School,Charter,1635,1043130,39147,Raymond Hawkins,M,10th,88,81
39148,14,Thomas High School,Charter,1635,1043130,39148,Christopher Wilson,M,10th,89,89
39149,14,Thomas High School,Charter,1635,1043130,39149,Glenda Fletcher,F,11th,82,93
39150,14,Thomas High School,Charter,1635,1043130,39150,Jennifer Hamilton,F,11th,80,75
39151,14,Thomas High School,Charter,1635,1043130,39151,Shannon Williams,F,10th,84,73
39152,14,Thomas High School,Charter,1635,1043130,39152,Lori Moore,F,9th,98,84
39153,14,Thomas High School,Charter,1635,1043130,39153,William Hubbard,M,9th,80,75
39154,14,Thomas High School,Charter,1635,1043130,39154,Bradley Johnson,M,12th,91,71
39155,14,Thomas High School,Charter,1635,1043130,39155,John Brooks,M,10th,92,98
39156,14,Thomas High School,Charter,1635,1043130,39156,Stephanie Contreras,F,11th,79,95
39157,14,Thomas High School,Charter,1635,1043130,39157,Kristen Gonzalez,F,9th,79,94
39158,14,Thomas High School,Charter,1635,1043130,39158,Kari Holloway,F,10th,87,90
39159,14,Thomas High School,Charter,1635,1043130,39159,Kimberly Cabrera,F,11th,85,72
39160,14,Thomas High School,Charter,1635,1043130,39160,Katie Weaver,F,11th,89,86
39161,14,Thomas High School,Charter,1635,1043130,39161,April Reyes,F,10th,70,84
39162,14,Thomas High School,Charter,1635,1043130,39162,Derek Weeks,M,12th,94,77
39163,14,Thomas High School,Charter,1635,1043130,39163,John Reese,M,11th,90,75
39164,14,Thomas High School,Charter,1635,1043130,39164,Joseph Anthony,M,9th,97,76
39165,14,Thomas High School,Charter,1635,1043130,39165,Donna Howard,F,12th,99,90
39166,14,Thomas High School,Charter,1635,1043130,39166,Dawn Bell,F,10th,95,70
39167,14,Thomas High School,Charter,1635,1043130,39167,Rebecca Tanner,F,9th,73,84
39168,14,Thomas High School,Charter,1635,1043130,39168,Desiree Kidd,F,10th,99,90
39169,14,Thomas High School,Charter,1635,1043130,39169,Carolyn Jackson,F,11th,95,75

In [11]:
# * Create a high level snapshot (in table form) of the district's key metrics, including:
#   * Total Schools
#   * Total Students
#   * Total Budget
#   * Average Math Score
#   * Average Reading Score
#   * % Passing Math
#   * % Passing Reading
#   * Overall Passing Rate (Average of the above two)

total_schools = len(school_df["name"])
total_students = len(students_df["name"])  #sum(school_df["size"])
total_budget = sum(school_df["budget"])
avg_math = students_df["math_score"].mean()
avg_reading = students_df["reading_score"].mean()
pct_math = (len(students_df[(students_df['math_score'] >= passing_rate)]) / total_students)

pct_reading = (len(students_df[(students_df['reading_score'] >= passing_rate)]) / total_students)
overall_passing = (pct_math + pct_reading) / 2

In [12]:
# **District Summary**
district_summary = {

    "Total Schools": (total_schools),
    "Total Students": (total_students),
    "Total Budget": (total_budget),
    "Average Math Score": (avg_math),
    "Average Reading Score": (avg_reading),
    "% Passing Math": (pct_math),
    "% Passing Reading": (pct_reading),
    "Overall Passing Rate": (overall_passing)
    
}
ds_df = pd.DataFrame([district_summary], 
                     columns=["Total Schools","Total Students","Total Budget","Average Math Score","Average Reading Score","% Passing Math","% Passing Reading","Overall Passing Rate"])

ds_df.style.format({"% Passing Math": "{:.2%}", "% Passing Reading": "{:.2%}", "Overall Passing Rate": "{:.2%}", "Total Budget":"${:}" })

In [27]:
# * Create an overview table that summarizes key metrics about each school, including:
#   * School Name
#   * School Type
#   * Total Students
#   * Total School Budget
#   * Per Student Budget
#   * Average Math Score
#   * Average Reading Score
#   * % Passing Math
#   * % Passing Reading
#   * Overall Passing Rate (Average of the above two)

school_sum_df = school_df[["name", "type","size","budget"]]

#school_sum_df = school_sum_df.rename(columns = {"name":"name","type":"School Type","size":"Total Students","budget":"Total School Budget"})
#school_sum_df.set_index("", inplace=True)
school_sum_df["Per Student Budget"]=(school_sum_df["budget"] /school_sum_df["size"])

#school_sum_df
#school_sum_df["Average Math Score"] = (students_df[  (students_df['math_score'] >= passing_rate) & (students_df['school'] == school_sum_df["name"]) ])
#school_sum_df["Average Math Score"] = [(students_df[  (students_df['math_score'] >= passing_rate) & (students_df['school'] == s_name) ]).mean for s_name in school_sum_df["name"]]
school_sum_df["Average Math Score"] = [students_df[(students_df['school'] == s_name)]['math_score'].mean() for s_name in school_sum_df["name"]]
school_sum_df["Average Reading Score"] = [students_df[(students_df['school'] == s_name)]['reading_score'].mean() for s_name in school_sum_df["name"]]


#school_sum_df["% Passing Math"] = [students_df[(students_df['school'] == s_name)]['math_score'].mean() for s_name in school_sum_df["name"]]
school_sum_df["% Passing Math"] = [ len(
                                    students_df[
                                        (students_df['school'] == school_sum_df["name"][i]) &
                                    
                                    (students_df['math_score'] >= passing_rate)]) / school_sum_df['size'][i]
                        
                        
                                    for i in range(school_sum_df["name"].count())]

school_sum_df["% Passing Reading"] = [ len(
                                    students_df[
                                        (students_df['school'] == school_sum_df["name"][i]) &
                                    
                                    (students_df['reading_score'] >= passing_rate)]) / school_sum_df['size'][i]
                        
                        
                                    for i in range(school_sum_df["name"].count())]

school_sum_df["Overall Passing Rate"] = (school_sum_df["% Passing Reading"] + school_sum_df["% Passing Math"]) /2

school_sum_df

,name,type,size,budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,Huang High School,District,2917,1910635,655.0,76.629414,81.182722,0.888584,1.0,0.944292
1,Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,0.884368,1.0,0.942184
2,Shelton High School,Charter,1761,1056600,600.0,83.359455,83.725724,1.000000,1.0,1.000000
3,Hernandez High School,District,4635,3022020,652.0,77.289752,80.934412,0.890831,1.0,0.945415
4,Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,1.000000,1.0,1.000000
5,Wilson High School,Charter,2283,1319574,578.0,83.274201,83.989488,1.000000,1.0,1.000000
6,Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,1.000000,1.0,1.000000
7,Bailey High School,District,4976,3124928,628.0,77.048432,81.033963,0.895297,1.0,0.947649
8,Holden High School,Charter,427,248087,581.0,83.803279,83.814988,1.000000,1.0,1.000000
9,Pena High School,Charter,962,585858,609.0,83.839917,84.044699,1.000000,1.0,1.000000
10,Wright High School,Charter,1800,1049400,583.0,83.682222,83.955000,1.000000,1.0,1.000000
11,Rodriguez High School,District,3999,2547363,637.0,76.842711,80.744686,0.885471,1.0,0.942736
12,Johnson High School,District,4761,3094650,650.0,77.072464,80.966394,0.891829,1.0,0.945915
13,Ford High School,District,2739,1763916,644.0,77.102592,80.746258,0.893027,1.0,0.946513
14,Thomas High School,Charter,1635,1043130,638.0,83.418349,83.848930,1.000000,1.0,1.000000

In [30]:
school_sum_df.sort_values(by='Overall Passing Rate', ascending=False).head(5)

,name,type,size,budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
2,Shelton High School,Charter,1761,1056600,600.0,83.359455,83.725724,1.0,1.0,1.0
4,Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,1.0,1.0,1.0
5,Wilson High School,Charter,2283,1319574,578.0,83.274201,83.989488,1.0,1.0,1.0
6,Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,1.0,1.0,1.0
8,Holden High School,Charter,427,248087,581.0,83.803279,83.814988,1.0,1.0,1.0

In [31]:
school_sum_df.sort_values(by='Overall Passing Rate', ascending=True).head(5)

,name,type,size,budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
1,Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,0.884368,1.0,0.942184
11,Rodriguez High School,District,3999,2547363,637.0,76.842711,80.744686,0.885471,1.0,0.942736
0,Huang High School,District,2917,1910635,655.0,76.629414,81.182722,0.888584,1.0,0.944292
3,Hernandez High School,District,4635,3022020,652.0,77.289752,80.934412,0.890831,1.0,0.945415
12,Johnson High School,District,4761,3094650,650.0,77.072464,80.966394,0.891829,1.0,0.945915

In [ ]:
#math_by_grade = [{school:{grade:students_df.loc[(students_df['school'] == school) &(students_df['grade'] == grade)]["math_score"].mean()} for grade in students_df["grade"].unique()} for school in students_df["school"].unique()]


#math_by_grade#["Bailey High School"]


#test = pd.DataFrame.from_dict(math_by_grade)
#test#["Bailey High School"]

#test2 = pd.DataFrame.from_dict(test)

#test2